export class LanguageMap {
    public static OTHER:string = "devicon-plain";
    public static NPM:string = "npm-original-wordmark";
    public static IONIC:string = "ionic-original";
    public static EMBER:string = "ember-original-wordmark";
    public static ELECTRON:string = "electron-original";
    public static VAGRANT:string = "vagrant-plain";
    public static YARN:string = "yarn-plain";
    public static HANDLEBARS:string = "handlebars-plain";
    public static COUCH:string = "couchdb-plain";
    public static ELM:string = "elm-plain";
    public static CAKEPHP:string = "cakephp-plain";
    public static STYLUS:string = "stylus-original";
    public static EXPRESS:string = "express-original";
    public static PYCHARM:string = "pycharm-plain";
    public static RUBYMINE:string = "rubymine-plain";
    public static TOMCAT:string = "tomcat-line";
    public static VUE:string = "vuejs-plain";
    public static SWIFT:string = "swift-plain";
    public static WEBPACK:string = "webpack-plain";
    public static PROTRACTOR:string = "protractor-plain";
    public static CUCUMBER:string = "cucumber-plain";
    public static GRADLE:string = "gradle-plain";
    public static GITHUB:string = "github-original";
    public static D3JS:string = "d3js-plain";
    public static AWS:string = "amazonwebservices-original";
    public static ANDROID:string = "android-plain";
    public static ANGULAR:string = "angularjs-plain";
    public static APACHECONF:string = "apache-plain";
    public static APPLE:string = "apple-original";
    public static BABEL:string = "babel-plain";
    public static BACKBONE:string = "backbonejs-plain";
    public static BOWER:string = "bower-plain";
    public static C:string = "c-plain";
    public static COFFEESCRIPT:string = "coffeescript-original";
    public static CPLUSPLUS:string = "cplusplus-plain";
    public static CSHARP:string = "csharp-plain";
    public static CSS:string = "css3-plain";
    public static DOCKERFILE:string = "docker-plain";
    public static DOTNET:string = "dot-net-plain";
    public static GO:string = "go-plain";
    public static GRUNT:string = "grunt-plain";
    public static GULP:string = "gulp-plain";
    public static HEROKU:string = "heroku-plain";
    public static HTML:string = "html5-plain";
    public static JAVA:string = "java-plain";
    public static ANTBUILTSYSTEM:string = "java-plain";
    public static JASMINE:string = "jasmine-plain";
    public static JAVASCRIPT:string = "javascript-plain";
    public static LESS:string = "less-plain-wordmark";
    public static METEOR:string = "meteor-plain";
    public static MOCHA:string = "mocha-plain";
    public static MONGODB:string = "mongodb-plain";
    public static MYSQL:string = "mysql-plain";
    public static NGINX:string = "nginx-original";
    public static NODE:string = "nodejs-plain";
    public static ORACLE:string = "oracle-original";
    public static PHP:string = "php-plain";
    public static POSTGRESQL:string = "postgresql-plain";
    public static PYTHON:string = "python-plain";
    public static RAILS:string = "rails-plain";
    public static RUBY:string = "ruby-plain";
    public static REACT:string = "react-original";
    public static REDIS:string = "redis-plain";
    public static SCSS:string = "sass-original";
    public static SASS:string = "sass-original";
    public static TRAVIS:string = "travis-plain";
    public static TYPESCRIPT:string = "typescript-plain";

    public static getIconClass(key:string):string {
        key = key.replace(/\+/gi, "plus");
        key = key.replace(/#/gi, "sharp");
        key = key.replace(/\s/gi, "");
        key = key.toUpperCase();

        return "devicon-" + (LanguageMap[key] || LanguageMap["OTHER"]);
    }
};
