export interface IRepoLanguageMapping {
    [key: string]: string;
}

const repoLanguageMap:IRepoLanguageMapping = {
    OTHER: "devicon-plain",
    NPM: "npm-original-wordmark",
    IONIC: "ionic-original",
    EMBER: "ember-original-wordmark",
    ELECTRON: "electron-original",
    VAGRANT: "vagrant-plain",
    YARN: "yarn-plain",
    HANDLEBARS: "handlebars-plain",
    COUCH: "couchdb-plain",
    ELM: "elm-plain",
    CAKEPHP: "cakephp-plain",
    STYLUS: "stylus-original",
    EXPRESS: "express-original",
    PYCHARM: "pycharm-plain",
    RUBYMINE: "rubymine-plain",
    TOMCAT: "tomcat-line",
    VUE: "vuejs-plain",
    SWIFT: "swift-plain",
    WEBPACK: "webpack-plain",
    PROTRACTOR: "protractor-plain",
    CUCUMBER: "cucumber-plain",
    GRADLE: "gradle-plain",
    GITHUB: "github-original",
    D3JS: "d3js-plain",
    AWS: "amazonwebservices-original",
    ANDROID: "android-plain",
    ANGULAR: "angularjs-plain",
    APACHECONF: "apache-plain",
    APPLE: "apple-original",
    BABEL: "babel-plain",
    BACKBONE: "backbonejs-plain",
    BOWER: "bower-plain",
    C: "c-plain",
    COFFEESCRIPT: "coffeescript-original",
    CPLUSPLUS: "cplusplus-plain",
    CSHARP: "csharp-plain",
    CSS: "css3-plain",
    DOCKERFILE: "docker-plain",
    DOTNET: "dot-net-plain",
    GO: "go-plain",
    GRUNT: "grunt-plain",
    GULP: "gulp-plain",
    HEROKU: "heroku-plain",
    HTML: "html5-plain",
    JAVA: "java-plain",
    ANTBUILTSYSTEM: "java-plain",
    JASMINE: "jasmine-plain",
    JAVASCRIPT: "javascript-plain",
    LESS: "less-plain-wordmark",
    METEOR: "meteor-plain",
    MOCHA: "mocha-plain",
    MONGODB: "mongodb-plain",
    MYSQL: "mysql-plain",
    NGINX: "nginx-original",
    NODE: "nodejs-plain",
    ORACLE: "oracle-original",
    PHP: "php-plain",
    POSTGRESQL: "postgresql-plain",
    PYTHON: "python-plain",
    RAILS: "rails-plain",
    RUBY: "ruby-plain",
    REACT: "react-original",
    REDIS: "redis-plain",
    SCSS: "sass-original",
    SASS: "sass-original",
    TRAVIS: "travis-plain",
    TYPESCRIPT: "typescript-plain"
};

export const RepoLanguageMap = repoLanguageMap;
